import './globals.css'
import { UsuarioProvider } from '../contexts/usuarioContext'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UsuarioProvider>{children}</UsuarioProvider>
      </body>
    </html>
  )
}